// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else {
      return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDydIyZ67EH_BPVoGvuFOELSsz77a7-uj0',
    appId: '1:910516599381:web:1e849d6f34aad5d13c72dc',
    messagingSenderId: '910516599381',
    projectId: 'udemy-ac28e',
    authDomain: 'udemy-ac28e.firebaseapp.com',
    storageBucket: 'udemy-ac28e.appspot.com',
    measurementId: 'G-Z2CQWBK39Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhpC63BgfC_vyhYWAKA_Jpbd25j1TrW4',
    appId: '1:277137886822:android:24e20af37a71f867bae7a7',
    messagingSenderId: '277137886822',
    projectId: 'look-back-90825',
    //storageBucket: 'udemy-ac28e.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );
}
