// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else {
      return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC3x9NHavWAkK5oc8R7oW9xyaLGjU3cbEw",
    authDomain: "look-back-90825.firebaseapp.com",
    projectId: "look-back-90825",
    storageBucket: "look-back-90825.appspot.com",
    messagingSenderId: "277137886822",
    appId: "1:277137886822:web:c4054c0502ea63d0bae7a7",
    measurementId: "G-KW7HBEQ55S"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhpC63BgfC_vyhYWAKA_Jpbd25j1TrW4',
    appId: '1:277137886822:android:24e20af37a71f867bae7a7',
    messagingSenderId: '277137886822',
    projectId: 'look-back-90825',
    //storageBucket: 'gs://look-back-90825.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );
}
